### ISSUE TITLE
Edit Profile Issue

### ISSUE THREAD

**Issue by Techchauhan** [StackExchange/stacks-utils#121]
While editing the profile and saving the Twitter link, we encountered an issue. The domain for Twitter has changed, and the current domain is now [https://x.com](https://x.com)/. However, the old domain is still being used, which results in a warning message. 

## Please see the screenshot below for reference.

![image](https://github.com/user-attachments/assets/803c2a9a-57c2-4522-af5c-142e22a75c66)

## I wasn't sure which repository was the right one to create the issue, so I picked one based on my understanding and created the issue. I kindly request the author to give me the opportunity to resolve this issue. 🥺

**Comment by giamir** [comment]
Thanks for the report. This is not the correct place to report bugs related to the Stack Exchange's sites. 
You can report the bug in Meta by asking a question: https://meta.stackexchange.com/questions/ask 

Closing this issue.
